const students=[['أحمد محمد علي','الصف التاسع / أ','92%','أحمد'],['سارة عبد الله','الصف السابع / ب','88%','سارة'],['خالد حسن صالح','الصف العاشر / أ','76%','خالد'],['ريم محمد قاسم','الصف الخامس / أ','95%','ريم'],['عبد الرحمن علي','الصف الثاني عشر / ب','84%','عبد']];
const subjects=[['اللغة العربية','12 وحدة دراسية','▤'],['الرياضيات','10 وحدات دراسية','∑'],['العلوم','8 وحدات دراسية','⚗'],['اللغة الإنجليزية','14 وحدة دراسية','A'],['التربية الإسلامية','9 وحدات دراسية','☾'],['الدراسات الاجتماعية','7 وحدات دراسية','⌖'],['الحاسوب','6 وحدات دراسية','⌘'],['التربية الوطنية','5 وحدات دراسية','⚑']];
const app=document.getElementById('app'), title=document.getElementById('pageTitle');
function dashboard(){return `<div class="welcome"><div><p class="eyebrow">الأحد، ٢٧ سبتمبر ٢٠٢٦</p><h1>مرحباً بك، محمد 👋</h1><p>إليك ملخص أداء المدرسة لهذا اليوم.</p></div><div class="date-chip">◷ الفصل الدراسي الأول 2026/2027</div></div><div class="stats"><div class="card stat-card"><div class="stat-head"><div class="stat-icon">♙</div><span class="trend">↑ 8.2%</span></div><h2>1,248</h2><p>إجمالي الطلاب</p></div><div class="card stat-card"><div class="stat-head"><div class="stat-icon">♧</div><span class="trend">↑ 4.5%</span></div><h2>86</h2><p>عدد المعلمين</p></div><div class="card stat-card"><div class="stat-head"><div class="stat-icon">▦</div><span class="trend">↑ 2.1%</span></div><h2>42</h2><p>الفصول الدراسية</p></div><div class="card stat-card"><div class="stat-head"><div class="stat-icon">◉</div><span class="trend">↑ 6.8%</span></div><h2>94.6%</h2><p>نسبة الحضور اليوم</p></div></div><div class="grid-2"><div class="card"><div class="card-title"><h3>متوسط التحصيل الدراسي</h3><button class="link">عرض التقرير ←</button></div><div class="chart">${[65,78,58,88,72,94,80].map((h,i)=>`<div class="bar-col"><div class="bar ${i===5?'highlight':''}" style="height:${h}%"></div><span>${['أول','ثان','ثالث','رابع','خامس','سادس','سابع'][i]}</span></div>`).join('')}</div></div><div class="card"><div class="card-title"><h3>آخر النشاطات</h3><button class="link">عرض الكل</button></div><div class="activity"><div class="activity-icon">✓</div><div><strong>تم تسجيل حضور الصف التاسع</strong><small>منذ ١٥ دقيقة · أ. فاطمة الزهراء</small></div></div><div class="activity"><div class="activity-icon">▤</div><div><strong>تم رفع اختبار الرياضيات</strong><small>منذ ساعة · أ. محمد الحكيمي</small></div></div><div class="activity"><div class="activity-icon">♙</div><div><strong>انضم ١٢ طالباً جديداً</strong><small>أمس · شؤون الطلاب</small></div></div></div></div>`}
function studentsView(){return `<div class="section-head"><div><p class="eyebrow">إدارة المجتمع المدرسي</p><h1>الطلاب</h1></div><button class="primary-btn" onclick="notify('تم فتح نموذج إضافة طالب')">＋ إضافة طالب</button></div><div class="card table-card"><div class="toolbar"><input class="search" placeholder="ابحث باسم الطالب..." oninput="filterRows(this.value)"><select class="filter"><option>كل الصفوف</option><option>الصف الأول</option><option>الصف الثاني عشر</option></select></div><table><thead><tr><th>الطالب</th><th>الصف والفصل</th><th>متوسط الدرجات</th><th>الحالة</th><th></th></tr></thead><tbody id="studentRows">${students.map(s=>`<tr><td><div class="person"><div class="avatar">${s[3][0]}</div><strong>${s[0]}</strong></div></td><td>${s[1]}</td><td>${s[2]}</td><td><span class="badge">نشط</span></td><td><button class="link" onclick="notify('تم فتح ملف الطالب')">عرض</button></td></tr>`).join('')}</tbody></table></div>`}
function curriculum(){return `<div class="section-head"><div><p class="eyebrow">المنهج اليمني</p><h1>المناهج والمواد الدراسية</h1></div><button class="primary-btn" onclick="notify('تم فتح نموذج إضافة مادة')">＋ إضافة مادة</button></div><p style="color:var(--muted);margin-top:-10px;margin-bottom:22px">المواد المعتمدة لجميع الصفوف من الأول إلى الثاني عشر.</p><div class="subject-grid">${subjects.map(s=>`<div class="subject"><div class="subject-icon">${s[2]}</div><h3>${s[0]}</h3><p>${s[1]} · المنهج اليمني</p></div>`).join('')}</div>`}
function classes(){return `<div class="section-head"><div><p class="eyebrow">العام الدراسي 2026/2027</p><h1>الصفوف والفصول</h1></div><button class="primary-btn" onclick="notify('تم فتح نموذج إضافة فصل')">＋ إضافة فصل</button></div><div class="class-grid">${Array.from({length:12},(_,i)=>`<div class="card class-card"><h3>الصف ${['الأول','الثاني','الثالث','الرابع','الخامس','السادس','السابع','الثامن','التاسع','العاشر','الحادي عشر','الثاني عشر'][i]}</h3><p>${i<6?'المرحلة الأساسية':'المرحلة الإعدادية والثانوية'} · ${i%3+1} فصول</p><div class="progress"><i style="width:${55+i*3}%"></i></div><p style="margin-top:8px">${55+i*3}% متوسط الحضور</p></div>`).join('')}</div>`}
function generic(label){return `<div class="section-head"><div><p class="eyebrow">إدارة المدرسة</p><h1>${label}</h1></div><button class="primary-btn" onclick="notify('تم تنفيذ العملية بنجاح')">＋ إضافة جديد</button></div><div class="card" style="text-align:center;padding:70px 20px"><div class="subject-icon" style="margin:0 auto 15px">▦</div><h3>مساحة ${label}</h3><p style="color:var(--muted)">يمكنك إدارة بيانات ${label} ومتابعة الأداء من هذه الصفحة.</p><button class="primary-btn" onclick="notify('سيتم تفعيل هذه الوحدة قريباً')">بدء الإدارة</button></div>`}
const views={dashboard:['لوحة التحكم',dashboard],students:['الطلاب',studentsView],curriculum:['المناهج والمواد',curriculum],classes:['الصفوف والفصول',classes],teachers:['المعلمون',()=>generic('المعلمون')],parents:['أولياء الأمور',()=>generic('أولياء الأمور')],schedule:['الجدول الدراسي',()=>generic('الجدول الدراسي')],reports:['التقارير',()=>generic('التقارير')]};
function render(view='dashboard'){const v=views[view]||views.dashboard;title.textContent=v[0];app.innerHTML=v[1]();document.querySelectorAll('.nav-item[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view));document.getElementById('sidebar').classList.remove('open')}
document.querySelectorAll('.nav-item[data-view]').forEach(x=>x.addEventListener('click',()=>render(x.dataset.view)));document.getElementById('menuToggle').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
function notify(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function filterRows(value){document.querySelectorAll('#studentRows tr').forEach(row=>row.style.display=row.textContent.includes(value)?'':'none')}
render();
